USE pizza_sales_db;
-- Q1: What is the total revenue generated so far?
-- SELECT SUM(p.price * od.quantity) AS total_revenue
-- FROM pizzas p
-- JOIN order_details od ON p.pizza_id = od.pizza_id;

-- Q2: How many total orders have been placed?
-- SELECT COUNT(DISTINCT order_id) AS total_orders
-- FROM order_details;

-- Q3: How many total pizzas have been sold (by quantity)?
-- SELECT SUM(quantity) AS total_pizzas
-- FROM order_details;

-- Q4: Which is the most expensive and least expensive pizza (with name)?
-- Most expensive
-- SELECT pt.name, p.price
-- FROM pizzas p
-- JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
-- ORDER BY p.price DESC
-- LIMIT 1;

-- Least expensive
-- SELECT pt.name, p.price
-- FROM pizzas p
-- JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
-- ORDER BY p.price ASC
-- LIMIT 1;

-- Q5: What is the average price of a pizza?
-- SELECT AVG(price) AS avg_price
-- FROM pizzas;

-- Q6: How many distinct pizza categories are there, and what are their names?
-- SELECT COUNT(DISTINCT category) AS total_categories, GROUP_CONCAT(DISTINCT category) AS category_names
-- FROM pizza_types;

-- Q7: How many distinct pizza sizes are available?
-- SELECT COUNT(DISTINCT size) AS pizza_sizes, GROUP_CONCAT(DISTINCT size) AS size_names
-- FROM pizzas;


-- Q8: What are the top 5 best-selling pizzas by quantity?
-- SELECT pt.name, SUM(od.quantity) AS best_selling_pizzas
-- FROM pizza_types pt
-- JOIN pizzas p ON pt.pizza_type_id = p.pizza_type_id
-- JOIN order_details od ON od.pizza_id = p.pizza_id
-- GROUP BY pt.name
-- ORDER BY best_selling_pizzas DESC
-- LIMIT 5;

-- Q9: What are the top 5 pizzas by revenue generated?
-- SELECT pt.name, SUM(p.price * od.quantity) AS top_five_pizza_revenue
-- FROM pizza_types pt
-- JOIN pizzas p ON pt.pizza_type_id = p.pizza_type_id
-- JOIN order_details od ON od.pizza_id = p.pizza_id
-- GROUP BY pt.name
-- ORDER BY top_five_pizza_revenue DESC
-- LIMIT 5;

-- Q10: What is the total revenue generated by each category?
-- SELECT pt.category AS categories, SUM(p.price * od.quantity) AS total_revenue
-- FROM pizza_types pt
-- JOIN pizzas p ON p.pizza_type_id = pt.pizza_type_id
-- JOIN order_details od ON od.pizza_id = p.pizza_id
-- GROUP BY categories;

-- Q11: How many pizzas were sold in each size?
-- SELECT p.size AS size, SUM(od.quantity) AS total_sold
-- FROM pizzas p
-- JOIN order_details od ON p.pizza_id = od.pizza_id
-- GROUP BY size;

-- Q12: Which day of the week has the highest number of orders?
-- SELECT DAYNAME(order_date) AS days, COUNT(DISTINCT order_id) AS highestnumbers_of_order
-- FROM orders
-- GROUP BY days
-- ORDER BY highestnumbers_of_order DESC;

-- Q13: Which hour of the day sees the highest number of orders?
-- SELECT HOUR(order_time) AS hour, COUNT(DISTINCT order_id) AS highestnumbers_of_order
-- FROM orders
-- GROUP BY hour
-- ORDER BY highestnumbers_of_order DESC;

-- Q14: Which month generated the highest revenue?
-- SELECT MONTHNAME(order_date) AS Month, SUM(quantity * price) AS total_revenue
-- FROM orders o
-- JOIN order_details od ON od.order_id = o.order_id
-- JOIN pizzas p ON p.pizza_id = od.pizza_id
-- GROUP BY Month
-- ORDER BY total_revenue DESC;

-- Q15: What is the average number of pizzas ordered per order?
-- SELECT SUM(quantity) / COUNT(DISTINCT order_id) AS avg_pizzas_per_order
-- FROM order_details;

-- -- Q16: Which pizza has the most ingredients?
-- SELECT name, (LENGTH(ingredients) - LENGTH(REPLACE(ingredients, ",", ""))) + 1 AS total_ingredients
-- FROM pizza_types
-- ORDER BY total_ingredients DESC
-- LIMIT 1;

-- -- Q17: What is the average order value (bill amount) per order?
-- SELECT SUM(p.price * od.quantity) / COUNT(DISTINCT od.order_id) AS avg_order_value
-- FROM order_details od
-- JOIN pizzas p ON p.pizza_id = od.pizza_id;


-- -- Q18: Calculate monthly revenue along with its running (cumulative) total.
-- WITH monthly_rev AS (
--     SELECT MONTH(o.order_date) AS month_number, MONTHNAME(o.order_date) AS month,
--            SUM(p.price * od.quantity) AS total_revenue
--     FROM pizzas p
--     JOIN order_details od ON p.pizza_id = od.pizza_id
--     JOIN orders o ON o.order_id = od.order_id
--     GROUP BY month_number, month
-- )
-- SELECT month, total_revenue,
--        SUM(total_revenue) OVER (ORDER BY month_number) AS running_total
-- FROM monthly_rev
-- ORDER BY month_number;


-- -- Q19: Rank pizzas within each category based on their revenue.
-- WITH pizzas_rnk AS (
--     SELECT pt.name, SUM(p.price * od.quantity) AS total_revenue, pt.category
--     FROM pizzas p
--     JOIN order_details od ON od.pizza_id = p.pizza_id
--     JOIN pizza_types pt ON pt.pizza_type_id = p.pizza_type_id
--     GROUP BY category, pt.name
-- )
-- SELECT name, category, total_revenue,
--        RANK() OVER (PARTITION BY category ORDER BY total_revenue DESC) AS ranked_pizza
-- FROM pizzas_rnk;


-- -- Q20: Find the top 3 highest revenue-generating pizzas in each category.
-- WITH pizza_revenue AS (
--     SELECT pt.name, pt.category, SUM(p.price * od.quantity) AS total_revenue
--     FROM pizzas p
--     JOIN order_details od ON od.pizza_id = p.pizza_id
--     JOIN pizza_types pt ON pt.pizza_type_id = p.pizza_type_id
--     GROUP BY pt.category, pt.name
-- ),
-- ranked_pizzas AS (
--     SELECT name, category, total_revenue,
--            RANK() OVER (PARTITION BY category ORDER BY total_revenue DESC) AS revenue_rnk
--     FROM pizza_revenue
-- )
-- SELECT * FROM ranked_pizzas
-- WHERE revenue_rnk <= 3;


-- -- Q21: What percentage does each category contribute to the total revenue?
-- WITH revenue AS (
--     SELECT pt.category, SUM(p.price * od.quantity) AS total_revenue
--     FROM pizza_types pt
--     JOIN pizzas p ON p.pizza_type_id = pt.pizza_type_id
--     JOIN order_details od ON od.pizza_id = p.pizza_id
--     GROUP BY pt.category
-- ),
-- revenue_pct AS (
--     SELECT category, total_revenue,
--            ROUND(total_revenue / SUM(total_revenue) OVER () * 100, 2) AS percent_of_total
--     FROM revenue
-- )
-- SELECT * FROM revenue_pct;


-- -- Q22: Calculate the month-over-month growth/decline in revenue (using LAG).
-- WITH month_rev AS (
--     SELECT MONTH(o.order_date) AS month_number, MONTHNAME(o.order_date) AS month_name,
--            SUM(p.price * od.quantity) AS total_revenue
--     FROM orders o
--     JOIN order_details od ON od.order_id = o.order_id
--     JOIN pizzas p ON p.pizza_id = od.pizza_id
--     GROUP BY month_number, month_name
-- ),
-- revenue AS (
--     SELECT month_number, month_name, total_revenue,
--            LAG(total_revenue) OVER (ORDER BY month_number) AS prev_month_revenue
--     FROM month_rev
-- )
-- SELECT month_number, month_name, total_revenue, prev_month_revenue,
--        ROUND((total_revenue - prev_month_revenue) / prev_month_revenue * 100, 2) AS growth_pct
-- FROM revenue;


-- Q23: Which orders had the highest quantity of pizzas (top 5 largest orders)?
-- with pizzas as (
-- select order_id,sum(quantity) as total_pizzas from order_details
-- group by order_id
-- )
-- select * from pizzas
-- order by total_pizzas desc
-- limit 5;


-- Q24: Did demand for any pizza vary by season?
-- with season_demand as (
-- select 
-- case 
-- when month(order_date) in (12,1,2) then 'winter'
-- when month(order_date) in (3,4,5) then 'spring'
-- when month(order_date) in (6,7,8) then 'summers'
-- when month(order_date) in (9,10,11) then 'fall'
-- end as season,
-- od.quantity from orders o
-- join order_details od on od.order_id=o.order_id
-- )
-- select season,sum(quantity)as total_pizza_sold from season_demand
-- group by season 
-- order by total_pizza_sold desc;



-- Q25: What is the busiest day and hour combination for orders?
-- with busiest as (
-- select count(distinct order_id) as total_orders,dayname(order_date) as day ,hour(order_time) as hours from orders
-- group by day,hours
-- order by total_orders desc
-- )
-- select * from busiest
-- limit 5;
